### ISSUE TITLE
I find that  the stride is 1 in your codes,how to process the situation stride is not equal to one in the DeconvNet part?

### ISSUE THREAD

**Issue by JacobianTang** [ChienliMa/DeConvNet#1]

**Comment by ChienliMa** [comment]
hi~ 
do you mean the pooling stride ? or the conv stride ? for the conv stride , i can simply add a param to fit the theano api. for the pooling stride, i need to change the algo .

this is just a toy for fun. i have never expecepted someone would use it . so the inner code is terrible. for anyone who want to try deconvnet, i recommend the author's MATLAB toolbox , which is accessible in his personal webpage .

however , if you think this is useful , i am willing to improve it. please leave a comment if you have any further demand.

cheers
ma

sent from my cell phone , please excuse me if there is any typo.

-------- 原始邮件 --------
发件人：JacobianTang notifications@github.com
时间：周一 3月16日 09:42
收件人：ChienliMa/DeConvNet DeConvNet@noreply.github.com
主题：[DeConvNet] I find that  the stride is 1,how to process the situation stride is not equal to one? (#1)

**Comment by JacobianTang** [comment]
In deconvolution part!I think the-size of  the restructured image is smaller than origin image if the stride is not equal to one!but if deconvolution stride is one ,theses  indeed  have same size when you implement full conv2d.

发自我的 iPhone

**Comment by ChienliMa** [comment]
ok, i will have a look at and fix it tonight.  : )
i am happy that you are interested in this.

thanks 
ma 

-------- 原始邮件 --------
发件人：JacobianTang notifications@github.com
时间：周一 3月16日 10:29
收件人：ChienliMa/DeConvNet DeConvNet@noreply.github.com
抄送："Chienli Ma(马千里)" maqianlie@gmail.com
主题：Re: [DeConvNet] I find that  the stride is 1 in your codes,how to process the situation stride is not equal to one in the DeconvNet part? (#1)

**Comment by JacobianTang** [comment]
I am sorry !can I inquire something about deconvolution net?I think the height and weight of the last layer(restructure begin with here)was 1?and only one feature map have a value which is the max-activation ,so the other feature maps Is zero in this layer!i think the reconstruction obtained from this layer is a patch of origin image?

发自我的 iPhone

**Comment by ChienliMa** [comment]
i am working on the situation that stride not equal one.
the output should be the part that yield max activation value. for cifa —10, it is almost the whole image.

Sent from my phone, please forgive me  if there ' s any typo. :)

-------- 原始邮件 --------
发件人：JacobianTang notifications@github.com
时间：周二 3月17日 11:23
收件人：ChienliMa/DeConvNet DeConvNet@noreply.github.com
抄送："Chienli Ma(马千里)" maqianlie@gmail.com
主题：Re: [DeConvNet] I find that  the stride is 1 in your codes,how to process the situation stride is not equal to one in the DeconvNet part? (#1)

**Comment by ChienliMa** [comment]
Hi, sorry for such a late update.

I pushed a new file `new_stage.py` which contain a class that support convolution stride.
A little difference in API but it should be easier to use.

It's a pity that I cannot test the new code because I do not have a computer with nvidia GPU beside to train a network with stride. Maybe the weekend I will pay a visit to the lab.

I am considering rewriting pool an uppool, which will take some time but will make the code more clear.

**Comment by JacobianTang** [comment]
举个例子：

20_20--->kernel 5_5+s(2)-->8_8--->max pooling (2_2+s(2))-->4_4--->kernel 2_2_s(1)->3_3--->max pooling(3_3 +s(3))-> 1*1

显然最后一层pooling层的1个节点对应的就是输入图像的整个区域，而通过反卷积，你即使采用全卷积，最大得到的区域大小也只会有12*12

而倒数第二池化层的，每个节点对应的是输入图像的7_7区域，而通过反卷积只能获得6_6的区域大小，这种尺寸上的改变，怎么处理了，这并没有获得和输入图像完全一样的图！

**Comment by ChienliMa** [comment]
第一个，我看得懂英文，也看得懂中文，并不需要用感叹号。
第二个，我说明白了之前的代码不支持带步长卷积操作。所以你指出的问题在之前的代码是存在的
第三个，昨晚我推了另一个版本的代码，那个代码在反卷之后增加了upsample，来解决带步长的反卷积的问题。我也说明了。好吧我没说是 `deconv with stride` 我只说了  `support convolution stride`，但是前向后向都一样的。
第四个，昨晚的代码的代码我没有经过测试，因为我现在的电脑不好跑模型训练而且我没去实验室。我也说明了。如果你在使用中发现任何bug或者有一个训练好的模型可以让我测试，请传给我。

**Comment by ChienliMa** [comment]
另外就是，这个东西我只是做来玩，没打算用作生产标准，所以你能发现内里API是很混乱，而且功能设计上并不好用。如果你真的喜欢，我可以花时间重写整个程序，改成theano风格的代码。不过最近我有点忙，抽不开身。或者说我技术不好，不能在短时间内完成，毕竟我只是转专业的小本。如果你急用deconvnet功能，请移步原作者个人主页，他有matlab工具包。

**Comment by JacobianTang** [comment]
你别激动，我只是偶尔看到你的博客，觉得你有细节，马修的代码比较混乱，好像也没有stride的处理，我只是发现了这个问题，跟你提一下而已，感谢你努力修改，叹号是我的习惯，如果有问题，还请原谅。至于这个模型我暂时不需要用，好奇发现了你的代码，十分感谢！我找个机会读读马修的代码再交流。
发自我的 iPhone

**Comment by ChienliMa** [comment]
是的，我激动了，因为我一开始就说明白了我的代码没有stride，所以无法理解为什么你要多次使用感叹号强调同一个问题。

马修的matlab其实不好安装。另外stride我没看，我只看他的pool和uppool的实现。

不清楚你使用DeConvNet要来干什么。
如果是可视化的话，理解网络的话，我觉得效果挺好。不过现在这个deep
learning的领域已经变成大公司跑模型，然后各个实验室下载模型做应用，没有留给研究人员自己调出state-of-art的机会。
如果是定位的话，14年还是13年的imagenet
challenge有一篇论文用的是直接对输出结果求输入的偏导，结果是标签物体区域高亮。尽管他们试验效果很好，而且表示Deconvnet原理同他们论文差不多，但是那个结果我并不能复现，而且我个人觉得数学上有问题。
RNN我不能理解，毕竟半年没看论文了，而且决定不走DL这个方向。（人太蠢）

另外，你是从wordpress看到我的文章？因为要翻墙，我那个博客很久不更新，想不到还有人看。十分感谢你的关注 :)
有空我会更新代码，不过首先得吧cifa10的带stride的样本跑一次。

在 2015年3月21日 上午12:07，JacobianTang notifications@github.com写道：

**Comment by ChienliMa** [comment]
说一点私人的，看来你是时差党，而且是在北美。
下学期我也飞过去了，目前在等ad。
不介意的话交个朋友。
你们平时用什么工具聊天？可以私下email发过来。

在 2015年3月21日 上午12:58，Ma ChienLi maqianlie@gmail.com写道：
